@startuml diagrama
skinparam Linetype ortho
class Utilizador {
  - login: String
  - password: String
  - nome: String
  - estado: boolean
  - email: String
  - tipo: String
  + Utilizador(login: String, password: String, nome: String, estado: boolean, email: String, tipo: String)
  + getLogin(): String
  + getPassword(): String
  + getNome(): String
  + getEstado(): String
  + getEmail(): String
  + getTipo(): String
  + setLogin()
  + setPassword()
  + setNome()
  + setEstado()
  + setEstado(estado: boolean)
  + loggedUserLoop(user: Utilizador)
  + registerNewUser(estado: String, type: String): Utilizador
}

class Cliente extends Utilizador {
  - NIF: String
  - morada: String
  - telefone: String
  + Cliente(login: String, password: String, nome: String, estado: String, email: String, tipo: String, NIF: String, morada: String, telefone: String)
  + getNIF(): String
  + getMorada(): String
  + getTelefone(): String
  + setNIF()
  + setMorada()
  + setTelefone()
  + loggedUserLoop(user: Utilizador)
  + registerNewUser(estado: String, type: String): Cliente
  + editperfil(Utilizador user)
  + perfilUtilizador(Utilizador user)
  + realizarPedido()
  + consultarCompras()
}

class Tecnicos extends Utilizador {
  - NIF: String
  - morada: String
  - telefone: String
  + Tecnicos(login: String, password: String, nome: String, estado: String, email: String, tipo: String, NIF: String, morada: String, telefone: String)
  + getNIF(): String
  + getMorada(): String
  + getTelefone(): String
  + setNIF()
  + setMorada()
  + setTelefone()
  + loggedUserLoop(user: Utilizador)
  + registerNewUser(estado: String, type: String): Tecnicos
  + editperfil(Utilizador user)
  + perfilUtilizador(Utilizador user)
  + gerirEquipamentos()
  + gerirVendas()
  + processarPedido()
}

class Administrador extends Utilizador {
    +Administrador()
    +loggedUserLoop()
    +registerNewUser()
    +aprovarRegisto()
    +List<Utilizador> getUtilizadoresInativos()
    +perfilUtilizador(Utilizador user)
    +utilizadoresRegeditados()
    +editperfil(Utilizador user)
    +listagemUtilizadores()
    +aprovarPedidos()
    +gerirVendas()
    +associarTecnico()
}

class Main {
        +main(String[] args)
        -mainLoop()
        +registerUser()
        +loginUser() Utilizador
        +pressEnterKey()
        +clearConsole()
    }

class Validator {
  - validators: Map<String, Function<String, Boolean>>
  + isValidEmail(email: String): boolean
  + isValidNIF(nif: String): boolean
  + isValidIntegerNumeric(value: String): boolean
  + isValidFloatNumeric(value: String): boolean
  + isValidPhoneNumber(phoneNumber: String): boolean
  + isValidName(name: String): boolean
  + isValidLogin(login: String): boolean
  + isValidAddress(address: String): boolean
  + isValidMarca(marca: String): boolean
  + isValidModelo(modelo: String): boolean
  + isValidObs(observacoes: String): boolean
  + validatePassword(type: String): String
  + validateInput(typeString: String): String
  - encryptPassword(password: String): String
  + isLoginUnique(String login): boolean
  + isEmailUnique(String email): boolean
  + isNIFUnique(String nif): boolean
  + isPhoneNumberUnique(String phoneNumber): boolean
  + isCodigoEquipamentoUnico(String codigo): boolean
  + isValueUnique(String type, String value): boolean
}

class Ficheiros {
  + doUsersExist()
  + insertUserFicehiro(Sistema sistema)
  + insertObjectFicheiro(Sistema sistema)
  + authenticateUser(String login, String password)
  + carregarDadosSistema()
}

class Input {
  - scanner: Scanner
  - fileReader: BufferedReader
  - fileWriter: BufferedWriter
  - getScanner(): Scanner
  + readLine(): String
  + readInt(): int
  + hasNextInt(): boolean
  + closeScanner()
  + clearBuffer()
  + openFIleReade(filename: String)
  + readFileLine(): String
  + writeFileLine(String line)
  + closeFile()
  + openFileWriter(filename: String) : ObjectOutputStream
}

class Sistema {
  -List~Utilizador~ utilizadores
  -List~Servico~ servicos
  -List~Equipamentos~ equipamentos
  -List~Categoria~ categorias
  -List~Fornecedor~ fornecedores
  - static Sistema sistema
  +getInstance()
  +setInstance()
  +Sistema()
  +save()
  +adicionarUtilizador()
  +adicionarEquipamento()
  +adicionarCategoria()
  +adicionarServico()
  +carregarDados()
  +buscarUtilizadorPorLogin()
  +autenticarUtilizador()
}

enum EstadoServico {
    SUBMETIDO
    ACEITE
    CONCLUIDO
}

class Servico {
        -int codigo
        -Date dataPedido
        -String descricao
        -EstadoServico estado
        -double tempoProcessamento
        -double valorTotal
        -List~Equipamento~ equipamentos
        -List~Integer~ quantidades
        -List~SubServico~ subServicos
        -Tecnico tecnicoResponsavel
}

class SubServico{
    String designacao
    Tecnico tecnicoResponsavel
}

class Equipamentos {
    -String marca
    -String modelo
    -String codigoInterno
    -Serie serie
    -Versao versao
    -float voltagem
    -int quantidadeStock
    -float precoVenda
    -String observacoes
    -boolean isOEM
    -List~Fornecedor~ fornecedores
    -List~Categoria~ categorias
    +Equipamentos(marca: String, modelo: String, codigoInterno: String, serie: Serie, versao: Versao, voltagem: double, quantidadeStock: int, precoVenda: double, observacoes: String, isOEM: boolean)
    +getMarca(): String
    +getModelo(): String
    +getCodigoInterno(): String
    +getSerie(): Serie
    +getVersao(): Versao
    +getVoltagem(): double
    +getQuantidadeStock(): int
    +getPrecoVenda(): double
    +getObservacoes(): String
    +getIsOEM(): boolean
    +getFornecedores(): List~Fornecedor~
    +getCategorias(): List~Categoria~
    +setQuantidadeStock()
    +addrFornecedor()
    +handleFornecedorSelection()
    +addCategoria()
    +handleCategoriaSelection()
    +addinforEquipamento()
    +select(): int
    +addEquipamentos(): Equipamento
    +listarEquipamentos()
    +equipamentosLoop()
    +toString(): String
    +atualizarStock()
    +listarEquipamentosLoop()
}

class Fornecedor {
    -String nome
    -String morada
    -String telefone
    +Fornecedor(nome: String, morada: String, telefone: String)
    +getNome(): String
    +getMorada(): String
    +getTelefone(): String
    +setNome()
    +setMorada()
    +setTelefone()
    +listarfornecedores()
    +adicionarFornecedor():Fornecedor
    +toString(): String
}

class Categoria {
    -String designacao
    -String familia
    +Categoria(designacao: String, familia: String)
    +getDesignacao(): String
    +getFamilia(): String
    +setDesignacao()
    +setFamilia()
    +adicionarCategoria():Categoria
    +listarCategorias()
    +toString(): String
}

class Serie {
    -int geracao
    -int sequencia
    +Serie(geracao: int, sequencia: int)
    +adicionarSerie():Serie
    +toString(): String
}

class Versao {
    -int unidade
    -int valorAlfa
    -int valorBeta
    +versao(unidade: int, valorAlfa: int, valorBeta: int)
    +adicionarVersao():Versao
    +toString(): String
}

Sistema -- Utilizador
Sistema -- Servico
Sistema -- Equipamentos
Sistema <-- Ficheiros
Main --> Input
Main -- Validator
Tecnicos --> Validator
Tecnicos -- Servico
Tecnicos --> Sistema
Cliente --> Validator
Cliente --> Servico
Cliente -- Sistema
Administrador --> Validator
Administrador --> Sistema
Validator --> Input
Ficheiros --> Input
Utilizador --> Input
Equipamentos --> Fornecedor
Equipamentos --> Categoria
Equipamentos --> Serie
Equipamentos --> Versao
Servico -- Equipamentos
Categoria <-- Sistema
Fornecedor <-- Equipamentos
Fornecedor -- Input
Fornecedor <-- Sistema
SubServico <-- Servico
Servico --> EstadoServico